INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(1, 'Energetyka', 'FIRST', 'FT', 'ENG', 4);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(2, 'Inżynieria materiałowa', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(3, 'Inżynieria mechaniczno-medyczna', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(4, 'Mechanika i budowa maszyn', 'FIRST', 'FT', 'ENG', 6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(5, 'Mechanika i budowa maszyn', 'FIRST', 'PT', 'ENG', 6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(6, 'Mechatronika', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(7, 'Oceanotechnika', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(8, 'Oceanotechnika', 'FIRST', 'PT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(9, 'Projektowanie i budowa jachtów', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(10, 'Transport i logistyka', 'FIRST', 'FT', 'ENG', 6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(11, 'Zarządzanie i inżynieria produkcji', 'FIRST', 'FT', 'ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(22, 'Automatyka, cybernetyka i robotyka', 'FIRST', 'FT', 'ENG', 4);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(23, 'Elektronika i telekomunikacja', 'FIRST', 'FT', 'ENG', 1);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(24, 'Informatyka', 'FIRST', 'FT', 'ENG', 1);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(25, 'Informatyka', 'FIRST', 'PT', 'ENG', 1);

INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(12, 'Energetyka', 'SECOND', 'FT', 'MGR_ENG', 4);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(13, 'Inżynieria materiałowa', 'SECOND', 'FT', 'MGR_ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(14, 'Inżynieria mechaniczno-medyczna', 'SECOND', 'FT', 'MGR_ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(15, 'Mechanika i budowa maszyn', 'SECOND', 'FT', 'MGR_ENG', 6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(16, 'Mechanika i budowa maszyn', 'SECOND', 'PT', 'MGR_ENG', 6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(17, 'Mechatronika', 'SECOND', 'FT', 'MGR_ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(18, 'Oceanotechnika', 'SECOND', 'FT', 'MGR_ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(19, 'Oceanotechnika', 'SECOND', 'PT', 'MGR_ENG', 7);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(20, 'Technologie kosmiczne i satelitarne', 'SECOND', 'FT', 'MGR_ENG', 5);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(21, 'Transport i logistyka', 'SECOND', 'FT', 'MGR_ENG'6);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(26, 'Automatyka, cybernetyka i robotyka', 'SECOND', 'FT', 'MGR_ENG', 4);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(27, 'Elektronika i telekomunikacja', 'SECOND', 'FT', 'MGR_ENG', 1);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(28, 'Informatyka', 'SECOND', 'FT', 'MGR_ENG', 1);
INSERT INTO fields_of_study (id, name, `level_of_education`, `study_mode`, `obtained_title`, department_id) VALUES(29, 'Informatyka', 'SECOND', 'PT', 'MGR_ENG', 1);