INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(1, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(2, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(3, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(4, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(5, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(6, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(7, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(8, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(9, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(10, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(11, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(12, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(13, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(14, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(15, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 45);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(16, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(17, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(18, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(19, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(20, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(21, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(22, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(23, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(24, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(25, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(26, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(27, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(28, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(29, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(30, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(31, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(32, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(33, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(34, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 15);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester) VALUES(35, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 15);
