INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(1, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 24);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(2, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 25);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(3, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 28);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(4, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 29);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(5, 'COMPUTER SCIENCE', 'Learning Java and Spring', 'FIRST', 45, 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(6, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 24);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(7, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 25);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(8, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 28);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(9, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 29);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(10, 'SYSTEMY INŻYNIERII WIEDZY', 'Learning Java and Spring', 'SECOND', 15, 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(11, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 24);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(12, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 25);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(13, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 28);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(14, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 29);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(15, 'SYSTEMY STEROWANIA I WSPOMAGANIA DECYZJI', 'Learning Java and Spring', 'THIRD', 15, 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(16, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(17, 'Technika wysokich napięć', 'Learning Java and Spring', 'FIRST', 60, 12);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(18, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 22);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(19, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 9);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(20, 'Technika wysokich napięć', 'Learning Java and Spring', 'FOURTH', 60, 23);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(21, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(22, 'Mechanika', 'Learning Java and Spring', 'SECOND', 30, 12);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(23, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 2);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(24, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 4);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(25, 'Mechanika', 'Learning Java and Spring', 'FIFTH', 30, 5);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(26, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(27, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 2);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(28, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 3);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(29, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 4);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(30, 'Inżynieria materiałowa', 'Learning Java and Spring', 'SIXTH', 5);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(31, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 1);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(32, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 24);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(33, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 25);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(34, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 23);
INSERT INTO subjects (id, name, description, `semester`, hours_in_semester, field_id) VALUES(35, 'Podstawy programowania', 'Learning Java and Spring', 'SEVENTH', 22);
