spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3307/classroom
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      platform: mysql
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          import_files: import/students.sql, import/teachers.sql, import/subjects.sql, import/import.sql